name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: prod
          - environment: dev
    environment:
      name: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cat README.md

