name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cat README.md
  deployment-prod:
    needs: [deployment-dev]
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cat README.md


